trigger:
- main   

pool:
  vmImage: 'ubuntu-latest'  

variables:
  buildConfiguration: 'Release'   

stages:
- stage: Build
  displayName: 'Build .NET App'
  jobs:                        
  - job: BuildJob
    displayName: 'Build .NET Job'
    steps:
    # Step 1: Install .NET 8 SDK
    - task: UseDotNet@2
      displayName: 'Install .NET 8 SDK'
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    # Step 2: Restore dependencies
    - task: DotNetCoreCLI@2
      displayName: 'Restore Dependencies'
      inputs:
        command: 'restore'
        projects: 'HelloWorldApp.csproj'

    # Step 3: Build project
    - task: DotNetCoreCLI@2
      displayName: 'Build .NET Project'
      inputs:
        command: 'build'
        projects: 'HelloWorldApp.csproj'
        arguments: '--configuration $(buildConfiguration)'

    # Step 4: Publish project (console app)
    - task: DotNetCoreCLI@2
      displayName: 'Publish .NET Project'
      inputs:
        command: 'publish'
        projects: 'HelloWorldApp.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

    # Step 5: Publish artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
